[트렌디 김정식] 1) Update: models.py 최종 수정 완료, 2) 상품리뷰 views.py, urls.py 작성 완료
wecode-bootcamp-korea/14-1st-Trendi-backend pull request #3
Opened 2020-11-19 17:07 UTC by Sik-Kim

1) 모든 App models.py 모델링 피드백 반영하여 최종 수정 완료
2) Review App의 views.py, urls.py 구현
 - 상품리뷰에 대한 CRUD입니다.
 - 프론트와 test 완료하였습니다.
 - 로그인 Decorator는 아직 반영하지 못했습니다.

2020-11-20 02:19 UTC, ulfrid requested changes
수정사항 확인 부탁드립니다!

2020-11-20 02:19 UTC, devops-andrew commented on order/models.py
> +    status = models.IntegerField()
상태값을 숫자로만 관리하는건 좋은 방법이 아닙니다.

2020-11-20 02:19 UTC, devops-andrew commented on order/views.py
> +class OrderStatusView(View):
이 뷰의 존재 이유를 설명해주세요.

2020-11-20 02:19 UTC, devops-andrew commented on order/views.py
> +            status_id
이뷰는 아직 완성되지 않은것 같네요. 확인 부탁드립니다.

2020-11-20 02:19 UTC, devops-andrew commented on review/views.py
> +        print("------request.body", request.body)
머지될 코드에 print출력은 포함되지 않도록 주의해주세요.
항상 main에 머지되는 코드는 최종 코드입니다.

2020-11-20 02:19 UTC, devops-andrew commented on review/views.py
> +            print("-----user_information---",user_information)
제거해주세요!

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +        # except Exception as ex:
주석처리 되어 있지만, 
이런식의 에러 캐치는 지양해주세요. 실제 운영하는데 이런 익셉션은 포함되선 안됩니다.
그냥 500을 만나시고, 잡아주세요.

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +            return JsonResponse({"message": "Review Success!!"}, status=200)
```suggestion
            return JsonResponse({"message": "SUCCESS"}, status=200)
```
바디로 리스판스하는 메세지는 사실 중복의미이지만, 클라이언트와 대화를 하는게 아닌 이 메세지 조차도 에러코드로 기억해주세요.
따라서 간단 명료한 메세지 코드로 작성해야 합니다.

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +            return JsonResponse({"message":"This nick_name is not exist!"}, status=400)
```suggestion
            return JsonResponse({"message":"INVALID_USER"}, status=400)
```
이렇게 수정해주세요. 메세지의 코드는 대문자에 띄어쓰기는 _ 로 구분해주세요.

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +            return JsonResponse({"message":"This product is not exist!"}, status=400)
```suggestion
            return JsonResponse({"message":"INVALID_PRODUCT"}, status=400)
```

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +            return JsonResponse({"message": "Key Error!!"}, status=400)
```suggestion
            return JsonResponse({"message": "INVALID_KEYS"}, status=400)
```

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +                review_list.append(review_data)
```
review_list = []
            for review in reviews:
                review_data = {
                    "content"   : review.content,
                    "image_url" : review.image_url,
                    "star"      : review.star,
                    "nick_name" : review.user.nick_name,
                    "product"   : review.product_id,
                    "updated_at": str(review.updated_at),
                    # "user_information": review.user_information
                }
                review_list.append(review_data)
```
위의 코드는 아래와 같이 변경해 봅시다! 
list comprehension을 아시나요?
실제로 코드도 간결해지고 속도도 빠른 파이써닉한 문법의 결정체입니다.
```
review_list = [{
                    "content"   : review.content,
                    "image_url" : review.image_url,
                    "star"      : review.star,
                    "nick_name" : review.user.nick_name,
                    "product"   : review.product_id,
                    "updated_at": str(review.updated_at),
                    # "user_information": review.user_information
                } for review in reviews]
```
같은 결과 입니다.

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +            return JsonResponse({"message": review_list}, status=200)
```suggestion
            return JsonResponse({"data": review_list}, status=200)
```

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +        except KeyError:
KeyError는 언제 발생할까요?

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +        except Exception as ex:
제거해주세요

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +        data = json.loads(request.body)
1. delete와 get 메소드는 body를 통해서 데이터 전달을 하지 않습니다.
2.그럼 어떻게 해야 할까요? query string이라는 것을 찾아보세요.
3. request.DELETE에도 쿼리스트링이 담길수 있습니다.
4. 대안으로 DELETE 메소드를 선언하지 않고 새로운 클래스를 선언해서 post 로 처리할수 있습니다. ex)class ReviewDeleteView

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +
익셉션들은 위에 언급한것들 잘 확인하셔서 정리해주시고, 메세지도 다듬어 주세요.

2020-11-20 02:19 UTC, ulfrid commented on review/views.py
> +            return JsonResponse({"extra error message": f"{ex}"}, status=400)
마찬가지입니다. 확인해주시면 다시 검토하겠습니다.

2020-11-20 04:22 UTC, Sik-Kim commented on order/models.py
> +    status = models.IntegerField()
네. 상태값으로 사용할 필드명이 마땅히 없어서 __str__ 메서드 삭제했습니다.

2020-11-20 04:23 UTC, Sik-Kim commented on order/views.py
> +class OrderStatusView(View):
해당뷰는 삭제했습니다!

2020-11-20 04:24 UTC, Sik-Kim commented on order/views.py
> +            status_id
넵. 아직 미완성입니다. 다음번엔 작성 완료된 것만 PR 하도록 하겠습니다.

2020-11-20 04:35 UTC, Sik-Kim commented on review/views.py
> +        print("------request.body", request.body)
삭제하겠습니다.😂

2020-11-20 04:35 UTC, Sik-Kim commented on review/views.py
> +            print("-----user_information---",user_information)
넵!😂

2020-11-20 04:36 UTC, Sik-Kim commented on review/views.py
> +        except Exception as ex:
넵!😂

2020-11-20 04:38 UTC, Sik-Kim commented on review/views.py
> +        except KeyError:
아... request body가 없으니 당연히 key도 없는 거군요.. 삭제하겠습니다!

2020-11-20 04:38 UTC, Sik-Kim commented on review/views.py
> +
넵 ㅎㅎ

2020-11-20 04:38 UTC, Sik-Kim commented on review/views.py
> +            return JsonResponse({"extra error message": f"{ex}"}, status=400)
넵!

2020-11-20 05:47 UTC, Sik-Kim commented on review/views.py
> +        data = json.loads(request.body)
query string 사용하여 엔드포인트 수정했습니다!

![image](https://user-images.githubusercontent.com/63498876/99763905-3e1db380-2b3f-11eb-9c39-e6755f7ef959.png)

2020-11-20 10:25 UTC, Sik-Kim commented on review/views.py
> +        # except Exception as ex:
네!!

2020-11-20 10:26 UTC, Sik-Kim commented on review/views.py
> +            return JsonResponse({"message": "Review Success!!"}, status=200)
넵

2020-11-20 10:27 UTC, Sik-Kim commented on review/views.py
> +            return JsonResponse({"message":"This nick_name is not exist!"}, status=400)
넵

2020-11-20 10:27 UTC, Sik-Kim commented on review/views.py
> +            return JsonResponse({"message":"This product is not exist!"}, status=400)
수정했습니다.

2020-11-20 10:27 UTC, Sik-Kim commented on review/views.py
> +            return JsonResponse({"message": "Key Error!!"}, status=400)
수정했습니다.

2020-11-20 10:28 UTC, Sik-Kim commented on review/views.py
> +            return JsonResponse({"message": review_list}, status=200)
반영했습니다.

2020-11-20 10:32 UTC, Sik-Kim commented on review/views.py
> +                review_list.append(review_data)
수정했습니다. list comprehension 아직 익숙치 않은데 연습 많이 하겠습니다. 😆

2020-11-24 08:27 UTC, soheon-lee commented on trendi/urls.py
> +>>>>>>> main
HEAD.........?

2020-11-24 09:55 UTC, soheon-lee commented on order/views.py
> +            order = Order.objects.filter(user=user, status_id=1)
코드 간격 정렬해주세요

2020-11-24 09:55 UTC, soheon-lee commented on order/views.py
> +            order = Order.objects.filter(user=user, status_id=1)
Order 객체를 필터링 할 때에는 user_id만 있어도 가능합니다. id를 사용하시면 26번째 줄에서 User 객체를 따로 가져오실 필요가 없어서 query를 아낄 수 있습니다. 이렇게 외래키로도 충분한 경우에는 객체를 가져오지 않는 것을 추천드립니다 :)

2020-11-24 09:55 UTC, soheon-lee commented on order/views.py
> +            orderlists = current_order.orderlist_set.all()
조건에 맞는 orderlist가 있으면 가져오고, 없으면 생성한 뒤 그 정보를 기입하는 내용이죠? good!
좋습니다. django에는 이렇게 `있으면 가져오고, 없으면 생성하는` 메소드가 있어서 이 과정을 보다 깔끔하게 처리하실 수 있습니다 :) 한 번 적용해보세요

2020-11-24 09:55 UTC, soheon-lee commented on order/views.py
> +            return JsonResponse({"message":"SUCCESS"}, status=200)
```suggestion
            return JsonResponse({"message":"SUCCESS"}, status=201)
```
어떤 데이터가 "생성"되었을 때는 201번 상태 코드를 한 번 사용해보세요

2020-11-24 09:55 UTC, soheon-lee commented on order/views.py
> +        #####
사용하지 않는 주석은 제거해주세요

2020-11-24 09:55 UTC, soheon-lee commented on order/views.py
> +            orderlists = OrderList.objects.filter(order=order)
주문한 상품을 조회하기 위해서 `User`, `Order`, `OrderList` 세 개의 클래스에 쿼리문을 날리고 있습니다.
이 방법 보다는 order 하나를 지칭 할 때에 유저 객체 대신 유저 id를 사용하거나, 그리고 그 order에 
orderlist를 조회할 때부터 애초에 user_id를 사용하는 방식을 도입해보세요 그렇게 되면 클래스 한 개에 접근하는 것만으로도 모든 데이터를 가져오실 수 있습니다.

2020-11-24 09:55 UTC, soheon-lee commented on order/views.py
> +            delivery_fee_calculator(orderlists, order)
`delete`에서 이 과정은 왜 진행하시는건가요?

2020-11-25 01:34 UTC, Sik-Kim commented on trendi/urls.py
> +>>>>>>> main
conflict 추가 수정했습니다.

2020-11-25 01:34 UTC, Sik-Kim commented on order/views.py
> +            order = Order.objects.filter(user=user, status_id=1)
넵..

2020-11-25 01:40 UTC, Sik-Kim commented on order/views.py
> +            return JsonResponse({"message":"SUCCESS"}, status=200)
넵ㅎㅎ

2020-11-25 01:40 UTC, Sik-Kim commented on order/views.py
> +        #####
😅

2020-11-25 02:52 UTC, Sik-Kim commented on order/views.py
> +            delivery_fee_calculator(orderlists, order)
장바구니에서 orderlist 삭제시 총금액 5만원이하로 될때 배송비를 0원에서 다시 2500원으로 변경하려고 넣었습니다.

2020-11-25 02:52 UTC, Sik-Kim commented on order/views.py
> +            orderlists = OrderList.objects.filter(order=order)
select_related 사용해서 한번 수정해보겠습니다.

2020-11-25 02:53 UTC, Sik-Kim commented on order/views.py
> +            orderlists = current_order.orderlist_set.all()
😱

2020-11-25 02:54 UTC, Sik-Kim commented on order/views.py
> +            order = Order.objects.filter(user=user, status_id=1)
네. 단순한 다른 클라스 필터용일때는 객체보다 id를 활용하도록 하겠습니다.

2020-11-25 17:56 UTC, Sik-Kim commented on order/views.py
> +            orderlists = current_order.orderlist_set.all()
소헌님.... 이거 장고 get_or_create 메소드 인거죠?
저는 db에 동일한 오더리스트가 있으면 수량만 올리고 없으면 오더리스트 생성 이런식으로 나누려고 아래와 같이 짜봤는데요.

            current_order = order.last()
            existing_orderlist,created = OrderList.objects.get_or_create(
                product=product,
                order=current_order,
                color_id=color_id,
                size_id=size_id,
                quantity=quantity
            )
            if not created:
                existing_orderlist.quantity += quantity
                existing_orderlist.save()
                print("====if not created 실행됨======")
            else:
                existing_orderlist
                print("====else 실행됨======")


이렇게하니 데이터가 있든없든 무조건 else만 실행되네요..
get_or_create 메소드만 단독으로 사용하는 방법은 알겠는데 if,else랑은 어떻게 같이 쓰는지 잘 모르게습니다...

![image](https://user-images.githubusercontent.com/63498876/100264614-66b80a00-2f92-11eb-8e18-674f3d39bbf0.png)


![image](https://user-images.githubusercontent.com/63498876/100265004-ee9e1400-2f92-11eb-8249-6509e9d126c0.png)

2020-11-26 03:03 UTC, Sik-Kim commented on order/views.py
> +            return JsonResponse({"message":"SUCCESS"}, status=200)
![image](https://user-images.githubusercontent.com/63498876/100303199-55491f00-2fdf-11eb-927a-9d97ef500308.png)

2020-11-26 11:32 UTC, soheon-lee commented on order/views.py
> +            "delivery_fee3"    : orderlist.order.delivery_fee
이건 어떤 의미인가요??

2020-11-26 11:32 UTC, soheon-lee commented on order/views.py
> +        orderlists = Order.objects.filter(user=request.user, orderstatus_id=1).last().orderlist_set.select_related('product__seller', 'product__delivery','size','color').all()
```suggestion
        orderlists = Order.objects.get(user=request.user, orderstatus_id=1).orderlist_set.select_related('product__seller', 'product__delivery','size','color').all()
```
어차피 대상이 하나뿐이므로 get을 사용해주셔도 좋습니다 :)

2020-11-26 11:32 UTC, soheon-lee commented on order/views.py
> +        orderlists = Order.objects.filter(user=request.user, orderstatus_id=1).last().orderlist_set.select_related('product__seller', 'product__delivery','size','color').all()
대신 Doesnot exist 에러는 잡아주셔야 할 것 같습니다

2020-11-26 11:32 UTC, soheon-lee commented on order/views.py
> +            quantity= data["quantity"]
```suggestion
            quantity = data["quantity"]
```

2020-11-26 11:32 UTC, soheon-lee commented on review/urls.py
> +    path("/<int:id>", ReviewView.as_view())
서로 다른 url이 같은 엔드포인트로 연결되는 것은 좋은 방법은 아닙니다. 클래스를 분리하시는 것을 추천드립니다

2020-11-26 11:32 UTC, soheon-lee commented on review/views.py
> +            star             = data["star"]
딕셔너리에 접근 하는 방법을 ['key'] 와 .get('key') 로 나눠서 작성하신 것은, 필수 적인 키인지 여부에 따라 다른 것인가요??

2020-11-26 11:32 UTC, soheon-lee commented on review/views.py
> +        } for review in reviews[::-1]]
`::-1`를 사용하신 이유가 순서를 반대로 정렬하시기 위한 것이라면, reviews를 처음 필터하실 때 정렬 기준을 제시하여 뽑아오시는 방법을 추천드립니다

2020-11-26 12:04 UTC, Sik-Kim commented on order/views.py
> +            "delivery_fee3"    : orderlist.order.delivery_fee
아.... 쿼리수 테스트 해보다가 안지웠습니다ㅠㅠ

2020-11-26 12:07 UTC, Sik-Kim commented on order/views.py
> +        orderlists = Order.objects.filter(user=request.user, orderstatus_id=1).last().orderlist_set.select_related('product__seller', 'product__delivery','size','color').all()
수정했습니다!

2020-11-26 12:07 UTC, Sik-Kim commented on order/views.py
> +            quantity= data["quantity"]
😇

2020-11-26 12:15 UTC, Sik-Kim commented on review/views.py
> +            star             = data["star"]
넵 image_url, user_information은 null=ture로 필수적인 키가 아니라 get 메소드 사용했습니다

2020-11-26 12:25 UTC, Sik-Kim commented on review/views.py
> +        } for review in reviews[::-1]]
def get(self, request, id):
        product_id = id
        reviews = Review.objects.select_related("user").filter(product=product_id).order_by("-updated_at")

이렇게 수정했습니다

2020-11-26 13:23 UTC, Sik-Kim commented on review/urls.py
> +    path("/<int:id>", ReviewView.as_view())
수정했습니다!

from django.urls import path
from .views import ReviewView, ReviewCreateView

urlpatterns = [
    path("/create", ReviewCreateView.as_view()),
    path("/<int:id>", ReviewView.as_view())
]

2020-11-26 15:59 UTC, soheon-lee commented
LGTM

2020-11-26 15:59 UTC, merged